name: Test for python versions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .
        pip install pytest
        
    - name: Install `gcsfuse`
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:gcsfuse/ppa
        sudo apt-get update
        sudo apt-get install -y gcsfuse fuse

    - name: Mount Google Cloud Storage bucket
      run: |
        mkdir -p /mnt/gcs-bucket
        gcsfuse --foreground --implicit-dirs genomics-public-data /mnt/gcs-bucket

    - name: List bucket contents
      run: ls /mnt/gcs-bucket

    - name: Download pytor file
      run: |
          wget https://storage.googleapis.com/cnvpytor_data/HepG2_WGS.pytor
    
    - name: check cnvpytor
      run: |
        cnvpytor -h

    - name: Run tests
      run: |
        pytest -s